name: Run ShellCheck
description: Lint shell scripts using shellcheck

inputs:
  path:
    description: Path to shell scripts or folder
    required: true
  output-file:
    description: Path to store the shellcheck output
    required: true
  name:
    description: Name of the artifact
    required: true
  enable-reviewdog:
    description: Enable ReviewDog PR comments
    required: false
    default: "false"
  github_token:
    description: GitHub token for ReviewDog
    required: false

runs:
  using: "composite"
  steps:
    - name: Install ShellCheck
      run: sudo apt-get install -y shellcheck
      shell: bash

    - name: Run ShellCheck
      env:
        path: ${{ inputs.path }}
        output-file: ${{ inputs.output-file }}
      run: |
        find ${path} -name "*.sh" | xargs shellcheck | tee ${output-file}
      shell: bash
      continue-on-error: true

    - name: Upload ShellCheck report
      if: always()
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: shellcheck-report-${{ inputs.name }}
        path: ${{ inputs.output-file }}

    - name: Run ReviewDog (ShellCheck)
      if: ${{ inputs.enable-reviewdog == 'true' }}
      uses: reviewdog/action-shellcheck@5ebd09ddbe2ebb471646ce234c6c8dd18663ca7c # 1.30.0
      with:
        github_token: ${{ inputs.github_token }}
        reporter: github-pr-review
        level: warning

