name: Run Yamllint
description: Lint YAML files using yamllint

inputs:
  path:
    description: Path to YAML files or folder
    required: true
  output-file:
    description: Path to store the yamllint output
    required: true
  name:
    description: Name of the artifact
    required: true
  enable-reviewdog:
    description: Enable ReviewDog PR comments
    required: false
    default: "false"
  github_token:
    description: GitHub token for ReviewDog
    required: false

runs:
  using: "composite"
  steps:
    - name: Install Yamllint
      run: sudo apt-get install -y yamllint
      shell: bash

    - name: Run Yamllint
      env:
        path: ${{ inputs.path }}
        output-file: ${{ inputs.output-file }}
      run: |
        yamllint ${path} | tee ${output-file}
      shell: bash
      continue-on-error: true

    - name: Upload Yamllint report
      if: always()
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: yamllint-report-${{ inputs.name }}
        path: ${{ inputs.output-file }}

    - name: Run ReviewDog (Yamllint)
      if: ${{ inputs.enable-reviewdog == 'true' }}
      uses: reviewdog/action-yamllint@f01d8a48fd8d89f89895499fca2cff09f9e9e8c0 # 1.21.0
      with:
        github_token: ${{ inputs.github_token }}
        reporter: github-pr-review
        level: warning
